### PR TITLE
test: Upgrade AKS cluster to Kubernetes v1.30

### PR DESCRIPTION
**Pull request by tomkerkhove**
Upgrade AKS cluster to Kubernetes v1.30.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Related to https://github.com/kedacore/keda/issues/5828

### CODE REVIEW

**Comment by JorTurFer** [comment]
We cannot merge this yet because AKS doesn't support 1.30:
image

Once Azure supports it we can merge this :)

**Comment by tomkerkhove** [comment]
It is supported: https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar

Maybe it's not live yet, let me check.

**Comment by JorTurFer** [comment]
Probably during next month: 
image

we don't use preview versions (at least yet) for e2e clusters

**Comment by tomkerkhove** [comment]
yes, just received that it is not ready yet.

**Comment by JorTurFer** [comment]
> yes, just received that it is not ready yet.

Do you know any ETA?

**Comment by tomkerkhove** [comment]
Soon

**Comment by JorTurFer** [comment]
The clusters are already using 1.30

**Pull request closed without merging**
