### PR TITLE
Added Application Registration to AzureAD for RabbitMQ testing purpose

### PR DESCRIPTION
**Pull request by kratkyzobak**
Added AzureAD Application Registration to enable test of Azure Workload Identity auth against RabbitMQ as proposed in https://github.com/kedacore/keda/pull/4657

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Related to https://github.com/kedacore/keda/pull/4657

### CODE REVIEW

**Comment by JorTurFer** [comment]
I guess that we will need to add more applications in the future. Could you create the module more abstract in order to reuse it?
I think that we can achieve it just moving this code to outside the module and passing it as variable:
```
application_name             = "${var.unique_project_name}-rabbitmq-app"
rabbitmq_roles = {
  management = "tag:management"
  administrator = "tag:administrator"
  read_all = "read:*/*/*"
  write_all = "write:*/*/*"
  configure_all = "configure:*/*/*"
}
```
(and renaming the resources, ofc)

**Comment by kratkyzobak** [comment]
@JorTurFer refactored to make it more generic module for app registraion.

**Review by JorTurFer — APPROVED** [review]
LGTM!

**Comment by JorTurFer** [comment]
There is an issue with the SP permission in our side, I'll update the issue once it's solved

**Comment by JorTurFer** [comment]
Done, the app has been created! 😄

**Pull request merged**
