### PR TITLE
Add AzureEventGrid Infra

### PR DESCRIPTION
**Pull request by SpiritZhou**
Add AzureEventGrid Infra for cloudevent-azureventgrid-test

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)

Related to # https://github.com/kedacore/keda/pull/5606

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]

**Comment by JorTurFer** [comment]
Please, execute `terraform fmt --recursive`, commit & push the changes.

**Comment by JorTurFer** [comment]
I have no idea about the required resources, could you confirm that these are correct?

- A ServiceBus topic in the main ServiceBus:  keda-e2e-receive-event-grid-topic
- A ServiceBus topic in the alternative ServiceBus (we use it for podidentity impersonation test):  keda-e2e-receive-event-grid-topic
- A new ServiceBus namespace: keda-e2e-servicebus-namespace-event-grid including
	- Azure Service Bus Data Owner role asignment
	- An authorizartion rule
	- A topic keda-e2e-receive-event-grid-topic
- An EventGrid subscription
- An EventGrid topic

**Comment by SpiritZhou** [comment]
> I have no idea about the required resources, could you confirm that these are correct?
> 
> * A ServiceBus topic in the main ServiceBus:  keda-e2e-receive-event-grid-topic
> * A ServiceBus topic in the alternative ServiceBus (we use it for podidentity impersonation test):  keda-e2e-receive-event-grid-topic
> * A new ServiceBus namespace: keda-e2e-servicebus-namespace-event-grid including
>   
>   * Azure Service Bus Data Owner role asignment
>   * An authorizartion rule
>   * A topic keda-e2e-receive-event-grid-topic
> * An EventGrid subscription
> * An EventGrid topic

Yes. What I want is creating a new event grid and a serviceBus topic to receive events.

**Comment by JorTurFer** [comment]
> Yes. What I want is creating a new event grid and a serviceBus topic to receive events.

Okey! In the future, I think that we can include a flag to deploy the topic or support providing the topics as input, but as topics don't have cost IIRC, we can continue with the PR as it is

**Pull request merged**
